### ISSUE TITLE
windows 対応

### ISSUE THREAD

**Issue by ynkdir** [mattn/libcallex-vim#1]
https://gist.github.com/ynkdir/effcb1301e27a5133b42

あらためて書き直したのでよかったらどうぞ。

浮動小数点数未対応。
showinfo.vim が動いてない感じです。バッファをわたして値を受け取るのはもう一工夫いりそうな気配。
64bit 版はポインタの扱いをなんとかしないとたぶん動かないかなと思います。Number 64bit 化期待。

そんな感じです。よろしくお願いします。

**Comment by ynkdir** [comment]
あ、もちろん libffi とか使った方が全然いいと思いますが、もしよかったらということで。
個人的な宿題だったので。

**Comment by mattn** [comment]
ありがとうございます。

あと arg が 6 以上の時どうするかも考えないとですね(mingw64)。

**Comment by ynkdir** [comment]
ラベルの名前がよくないですが arg5: は `while (narg >= 5) { push args[--narg] }` みたいな感じです。すみません。
あと今気づいたんですがたぶん mul とか使って配列のアドレス計算してるのはもっと簡単にかけそうですね。

**Comment by mattn** [comment]
あ、cmp ありましたね。すみません。

ちょっと試したところ CreateWindow が落ちる様ですね。

**Comment by ynkdir** [comment]
たぶん str2nr(a:instance) で 64bit から 32bit に落としてるからだと思います。

**Comment by ynkdir** [comment]
ああそか、エラーじゃなくて落ちてるのか。mmm

**Comment by mattn** [comment]
あ、HINSTANCE がポインタだから落ちて当然か

**Comment by ynkdir** [comment]
清書しました。

**Comment by ynkdir** [comment]
書き忘れ
そもそも何を修正するパッチなのか、ですが。
msvc x64 はインラインアセンブラが使えないのでそもそもコンパイルできなかったので別ファイルに。それに合わせて他のも別ファイルに。
x86 は cdecl 形式で call してたのを cdecl と stdcall どちらでも対応できるように修正。
です。

**Comment by ynkdir** [comment]
CreateWindow は str2nr(a:instance) を a:instance にしたら動きました。double になるのであれですけど。

**Comment by mattn** [comment]
ありがとうございます。試してみます。

**Comment by mattn** [comment]
merged. 9c2aea60a27a916791a1c71a16ecddbd71572ca5

**Comment by mattn** [comment]
メモリ渡す系のは別途考えます。

**Comment by ynkdir** [comment]
ユーザー空間のメモリアドレスは Windows でも Linux でも 47bit くらいで収まるぽいのでほとんどの場合は double でいけるのかもしれませんね。ユーザー空間とかカーネル空間とかよくわかりませんが。

仮想アドレス領域
https://msdn.microsoft.com/ja-jp/library/windows/hardware/hh439648.aspx

Linuxカーネルメモ - 64bitでのアドレス空間
http://wiki.bit-hive.com/linuxkernelmemo/pg/64bit%A4%C7%A4%CE%A5%A2%A5%C9%A5%EC%A5%B9%B6%F5%B4%D6

**Comment by mattn** [comment]
引数型は double と int と string しかサポートしていないので object を使って型と抱き合わせて値を引数に渡せる仕組みが必要そうですね。
